version: 2
jobs:
  indigo:
    docker:
      - image: ros:indigo-ros-core
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-get update && apt-get install openssh-client python-catkin-tools build-essential software-properties-common -y
            apt-add-repository -y ppa:jwhitleyastuff/linuxcan-dkms
            apt-get update && apt-get install -y linux-headers-generic linuxcan-dkms
            source `find /opt/ros -name setup.bash | sort | head -1`
            rosdep install --from-paths . --ignore-src -y
            cd ..
            catkin init
            catkin config --extend /opt/ros/$ROS_DISTRO
      - run:
          name: Build
          command: |
            cd ..
            catkin build
      - run:
          name: Run Tests
          command: |
            cd ..
            catkin run_tests
    working_directory: ~/src

  kinetic:
    docker:
      - image: ros:kinetic-ros-core
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-get update && apt-get install openssh-client python-catkin-tools build-essential software-properties-common -y
            apt-add-repository -y ppa:jwhitleyastuff/linuxcan-dkms
            apt-get update && apt-get install -y linux-headers-generic linuxcan-dkms
            source `find /opt/ros -name setup.bash | sort | head -1`
            rosdep install --from-paths . --ignore-src -y
            cd ..
            catkin init
            catkin config --extend /opt/ros/$ROS_DISTRO
      - run:
          name: Build
          command: |
            cd ..
            catkin build
      - run:
          name: Run Tests
          command: |
            cd ..
            catkin run_tests
    working_directory: ~/src

  lunar:
    docker:
      - image: ros:lunar-ros-core
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-get update && apt-get install openssh-client python-catkin-tools build-essential software-properties-common -y
            apt-add-repository -y ppa:jwhitleyastuff/linuxcan-dkms
            apt-get update && apt-get install -y linux-headers-generic linuxcan-dkms
            source `find /opt/ros -name setup.bash | sort | head -1`
            rosdep install --from-paths . --ignore-src -y
            cd ..
            catkin init
            catkin config --extend /opt/ros/$ROS_DISTRO
      - run:
          name: Build
          command: |
            cd ..
            catkin build
      - run:
          name: Run Tests
          command: |
            cd ..
            catkin run_tests
    working_directory: ~/src

  melodic:
    docker:
      - image: ros:melodic-ros-core
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-get update && apt-get install openssh-client python-catkin-tools build-essential software-properties-common -y
            apt-add-repository -y ppa:jwhitleyastuff/linuxcan-dkms
            apt-get update && apt-get install -y linux-headers-generic linuxcan-dkms
            source `find /opt/ros -name setup.bash | sort | head -1`
            rosdep install --from-paths . --ignore-src -y
            cd ..
            catkin init
            catkin config --extend /opt/ros/$ROS_DISTRO
      - run:
          name: Build
          command: |
            cd ..
            catkin build
      - run:
          name: Run Tests
          command: |
            cd ..
            catkin run_tests
    working_directory: ~/src

  indigo_release:
    docker:
      - image: ros:indigo-ros-core
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-get update && apt-get install build-essential software-properties-common dh-make python-bloom ruby -y
            apt-add-repository -y ppa:jwhitleyastuff/linuxcan-dkms
            apt-get update && apt-get install -y linux-headers-generic linuxcan-dkms
            gem install --no-rdoc --no-ri deb-s3
            source `find /opt/ros -name setup.bash | sort | head -1`
            rosdep install --from-paths . --ignore-src -y
      - run:
          name: Build
          command: |
            bloom-generate rosdebian --os-name ubuntu --os-version trusty --ros-distro indigo
            sed -i '/dh_shlibdeps -l.*/ s/$/ --dpkg-shlibdeps-params=--ignore-missing-info/' debian/rules
            fakeroot debian/rules binary
      - run:
          name: Upload
          command: |
            cd ..
            deb-s3 upload -b autonomoustuff-repo -c trusty --preserve-versions $(ls *.deb) --access-key-id=$S3_ACCESS_KEY_ID --secret-access-key=$S3_SECRET_ACCESS_KEY
    working_directory: ~/src

  kinetic_release:
    docker:
      - image: ros:kinetic-ros-core
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-get update && apt-get install build-essential software-properties-common dh-make python-bloom ruby -y
            apt-add-repository -y ppa:jwhitleyastuff/linuxcan-dkms
            apt-get update && apt-get install -y linux-headers-generic linuxcan-dkms
            gem install --no-rdoc --no-ri deb-s3
            source `find /opt/ros -name setup.bash | sort | head -1`
            rosdep install --from-paths . --ignore-src -y
      - run:
          name: Build
          command: |
            bloom-generate rosdebian --os-name ubuntu --os-version xenial --ros-distro kinetic
            sed -i '/dh_shlibdeps -l.*/ s/$/ --dpkg-shlibdeps-params=--ignore-missing-info/' debian/rules
            fakeroot debian/rules binary
      - run:
          name: Upload
          command: |
            cd ..
            deb-s3 upload -b autonomoustuff-repo -c xenial --preserve-versions $(ls *.deb) --access-key-id=$S3_ACCESS_KEY_ID --secret-access-key=$S3_SECRET_ACCESS_KEY
    working_directory: ~/src

  lunar_release:
    docker:
      - image: ros:lunar-ros-core
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-get update && apt-get install build-essential software-properties-common dh-make python-bloom ruby -y
            apt-add-repository -y ppa:jwhitleyastuff/linuxcan-dkms
            apt-get update && apt-get install -y linux-headers-generic linuxcan-dkms
            gem install --no-rdoc --no-ri deb-s3
            source `find /opt/ros -name setup.bash | sort | head -1`
            rosdep install --from-paths . --ignore-src -y
      - run:
          name: Build
          command: |
            bloom-generate rosdebian --os-name ubuntu --os-version xenial --ros-distro lunar
            sed -i '/dh_shlibdeps -l.*/ s/$/ --dpkg-shlibdeps-params=--ignore-missing-info/' debian/rules
            fakeroot debian/rules binary
      - run:
          name: Upload
          command: |
            cd ..
            deb-s3 upload -b autonomoustuff-repo -c xenial --preserve-versions $(ls *.deb) --access-key-id=$S3_ACCESS_KEY_ID --secret-access-key=$S3_SECRET_ACCESS_KEY
    working_directory: ~/src

  melodic_release:
    docker:
      - image: ros:melodic-ros-core
    steps:
      - checkout
      - run:
          name: Set Up Container
          command: |
            apt-get update && apt-get install build-essential software-properties-common dh-make python-bloom ruby -y
            apt-add-repository -y ppa:jwhitleyastuff/linuxcan-dkms
            apt-get update && apt-get install -y linux-headers-generic linuxcan-dkms
            gem install --no-rdoc --no-ri deb-s3
            source `find /opt/ros -name setup.bash | sort | head -1`
            rosdep install --from-paths . --ignore-src -y
      - run:
          name: Build
          command: |
            bloom-generate rosdebian --os-name ubuntu --os-version bionic --ros-distro melodic
            sed -i '/dh_shlibdeps -l.*/ s/$/ --dpkg-shlibdeps-params=--ignore-missing-info/' debian/rules
            fakeroot debian/rules binary
      - run:
          name: Upload
          command: |
            cd ..
            deb-s3 upload -b autonomoustuff-repo -c bionic --preserve-versions $(ls *.deb) --access-key-id=$S3_ACCESS_KEY_ID --secret-access-key=$S3_SECRET_ACCESS_KEY
    working_directory: ~/src

workflows:
  version: 2
  ros_build:
    jobs:
      - indigo:
          filters:
            branches:
              ignore: release
      - kinetic:
          filters:
            branches:
              ignore: release
      - lunar:
          filters:
            branches:
              ignore: release
      - melodic:
          filters:
            branches:
              ignore: release
  ros_release:
    jobs:
      - indigo_release:
          context: ubuntu-pkg-build
          filters:
            branches:
              only: release
      - kinetic_release:
          context: ubuntu-pkg-build
          filters:
            branches:
              only: release
      - lunar_release:
          context: ubuntu-pkg-build
          filters:
            branches:
              only: release
      - melodic_release:
          context: ubuntu-pkg-build
          filters:
            branches:
              only: release
